package_path: assets
package_assets: always

javascripts:
  base:
    - bower_components/jquery/jquery.js
    - bower_components/underscore/underscore.js
    - bower_components/backbone/backbone.js
    - bower_components/bootstrap/js/bootstrap-dropdown.js

stylesheets:
  bootstrap:
    - bower_components/bootstrap/bootstrap/css/bootstrap.css
